[build]
  publish = "build/"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
[build.environment]
  NPM_FLAGS = "--version"
[[redirects]]
  from = "/*"
  to = "/"
  status = 404
 
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=7776000"
